CREATE DATABASE project1;

USE project1;

CREATE TABLE Cars(
      Car_ID INT IDENTITY(1,1) PRIMARY KEY,
	  BRAND VARCHAR(255) NOT NULL,
	  MODEL VARCHAR(255) NOT NULL,
	  PricePerDay DECIMAL(10,2) NOT NULL,
	  SeatingCapacity INT NOT NULL
);

INSERT INTO Cars VALUES('Honda','Civic',40,5);
INSERT INTO Cars VALUES('Toyota','Camry',55,5);
INSERT INTO Cars VALUES('Ford','F-150',60,6);
INSERT INTO Cars VALUES('Suzuki','Swift',25,5);
INSERT INTO Cars VALUES('Honda','City',35,5);

SELECT * FROM Cars;



CREATE TABLE Users (
     USER_ID INT IDENTITY(1,1) PRIMARY KEY,
	 NAME VARCHAR(255) NOT NULL,
	 USER_NAME VARCHAR(255) NOT NULL,
	 PASSWORD VARCHAR(255) NOT NULL,
	 BALANCE DECIMAL(10,2) NOT NULL,
	 ADDRESS VARCHAR(255) NOT NULL,
	 Car_ID INT NULL,
	 CONSTRAINT FK_Users_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);
CREATE UNIQUE INDEX UQ_Users_Car_ID_NotNull
ON Users(Car_ID)
WHERE Car_ID IS NOT NULL;


INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES ('John Doe','JohnDoe','doe123',5890,'123 Main St',2);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Alice Wood','Alice!','thisisalice',2459,'456 Elm St',4);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Irfan Khan','IrfanJunior','junior7',3567,'Daisy St 6',5);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Sarah Todd','sarah_todd','todd789',90356,'789 Oak Ave',NULL);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Elaan Roy','royjoy','roy567',75790,'Broadway 911',NULL);

SELECT * FROM Users;

CREATE TABLE RentalHistory(
       Rental_ID INT IDENTITY(1,1) PRIMARY KEY,
	   USER_ID INT NOT NULL,
	   Car_ID INT NOT NULL,
	   START_DATE DATE NOT NULL,
	   END_DATE DATE NOT NULL,
	   CONSTRAINT FK_RentalHistory_Users FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
	   CONSTRAINT FK_RentalHistory_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);


INSERT INTO RentalHistory(USER_ID,Car_ID,START_DATE,END_DATE)
VALUES(3,5,'2025-02-03','2025-02-05');
INSERT INTO RentalHistory(USER_ID,Car_ID,START_DATE,END_DATE)
VALUES(1,2,'2025-03-15','2025-03-18');
INSERT INTO RentalHistory(USER_ID,Car_ID,START_DATE,END_DATE)
VALUES(2,4,'2025-02-12','2025-02-16');


SELECT * FROM RentalHistory;




       
