CREATE DATABASE project2;
GO

USE project2;
GO

CREATE TABLE Cars(
      Car_ID VARCHAR(255) PRIMARY KEY,
      BRAND VARCHAR(255) NOT NULL,
      MODEL VARCHAR(255) NOT NULL,
      PricePerDay_$ DECIMAL(10,2) NOT NULL,
      SeatingCapacity INT NOT NULL,
      ReservationStatus VARCHAR(255) NOT NULL
);
GO

INSERT INTO Cars VALUES('CR-HonCivic2024','Honda','Civic2024',40,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-ToyCamry2023','Toyota','Camry2023',55,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-ForF-150','Ford','F-150',60,6,'UNRESERVED');
INSERT INTO Cars VALUES('CR-SuzSwift2020','Suzuki','Swift2020',25,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-HonCity2022','Honda','City2022',35,5,'RESERVED');
GO

SELECT * FROM Cars;
GO

CREATE TABLE Users (
     NAME VARCHAR(255) NOT NULL,
     USER_NAME VARCHAR(255) PRIMARY KEY NOT NULL,
     PASSWORD VARCHAR(255) NOT NULL,
     BALANCE DECIMAL(10,2) NOT NULL,
     ADDRESS VARCHAR(255) NOT NULL,
     Car_ID VARCHAR(255) NULL,
     CONSTRAINT FK_Users_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);
GO

CREATE UNIQUE INDEX UQ_Users_Car_ID_NotNull
ON Users(Car_ID)
WHERE Car_ID IS NOT NULL;
GO

INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES ('John Doe','JohnDoe','JohnD@e92',5890,'123 Main St',NULL);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Alice Wood','Alice!','Alic3#Wood',2459,'456 Elm St',NULL);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Irfan Khan','IrfanJunior','Khan!Irf@n9',3567,'Daisy St 6','CR-HonCity2022');
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Sarah Todd','sarah_todd','S@rahT0dd!',90356,'789 Oak Ave',NULL);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Elaan Roy','royjoy','RoyElaan$7',75790,'Broadway 911',NULL);
GO

SELECT * FROM Users;
GO

CREATE TABLE RentalHistory(
       Rental_ID INT IDENTITY(1,1) PRIMARY KEY,
       USER_NAME VARCHAR(255) NOT NULL,
       Car_ID VARCHAR(255) NOT NULL,
       START_DATE DATE NOT NULL,
       END_DATE DATE NOT NULL,
       RENTAL_AMOUNT DECIMAL(10,2) NOT NULL,
       CONSTRAINT FK_RentalHistory_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID),
       CONSTRAINT FK_RentalHistory_Users FOREIGN KEY (USER_NAME) REFERENCES Users(USER_NAME)
);
GO

INSERT INTO RentalHistory(USER_NAME,Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('IrfanJunior','CR-HonCity2022','2025-05-12','2025-05-15',140);
INSERT INTO RentalHistory(USER_NAME,Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('JohnDoe','CR-ToyCamry2023','2025-03-15','2025-03-18',220);
INSERT INTO RentalHistory(USER_NAME,Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('Alice!','CR-SuzSwift2020','2025-02-12','2025-02-16',125);
GO

SELECT * FROM RentalHistory;
GO

CREATE TABLE Admin(
       Admin_ID INT IDENTITY(1,1) PRIMARY KEY,
       ADMIN_NAME VARCHAR(255) NOT NULL,
       PASSWORD VARCHAR(255) NOT NULL
);
GO

INSERT INTO Admin(ADMIN_NAME,PASSWORD)
VALUES('aam','1313@ned');
GO

SELECT * FROM Admin;
GO
