CREATE DATABASE project2;

USE project2;

CREATE TABLE Cars(
      Car_ID VARCHAR(255) PRIMARY KEY,
	  BRAND VARCHAR(255) NOT NULL,
	  MODEL VARCHAR(255) NOT NULL,
	  PricePerDay DECIMAL(10,2) NOT NULL,
	  SeatingCapacity INT NOT NULL,
	  ReservationStatus VARCHAR(255) NOT NULL
);

INSERT INTO Cars VALUES('CR-001','Honda','Civic',40,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-002','Toyota','Camry',55,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-003','Ford','F-150',60,6,'UNRESERVED');
INSERT INTO Cars VALUES('CR-004','Suzuki','Swift',25,5,'UNRESERVED');
INSERT INTO Cars VALUES('CR-005','Honda','City',35,5,'UNRESERVED');

SELECT * FROM Cars;



CREATE TABLE Users (
	 NAME VARCHAR(255) NOT NULL,
	 USER_NAME VARCHAR(255) PRIMARY KEY NOT NULL,
	 PASSWORD VARCHAR(255) NOT NULL,
	 BALANCE DECIMAL(10,2) NOT NULL,
	 ADDRESS VARCHAR(255) NOT NULL,
	 Car_ID VARCHAR(255) NULL,
	 CONSTRAINT FK_Users_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);
CREATE UNIQUE INDEX UQ_Users_Car_ID_NotNull
ON Users(Car_ID)
WHERE Car_ID IS NOT NULL;


INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES ('John Doe','JohnDoe','doe123',5890,'123 Main St','CR-002');
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Alice Wood','Alice!','thisisalice',2459,'456 Elm St','CR-004');
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Irfan Khan','IrfanJunior','junior7',3567,'Daisy St 6','CR-005');
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Sarah Todd','sarah_todd','todd789',90356,'789 Oak Ave',NULL);
INSERT INTO Users(NAME,USER_NAME,PASSWORD,BALANCE,ADDRESS,Car_ID)
VALUES('Elaan Roy','royjoy','roy567',75790,'Broadway 911',NULL);

SELECT * FROM Users;

CREATE TABLE RentalHistory(
       Rental_ID INT IDENTITY(1,1) PRIMARY KEY,
	   Car_ID VARCHAR(255) NOT NULL,
	   START_DATE DATE NOT NULL,
	   END_DATE DATE NOT NULL,
	   RENTAL_AMOUNT DECIMAL(10,2) NOT NULL,
	   CONSTRAINT FK_RentalHistory_Cars FOREIGN KEY (Car_ID) REFERENCES Cars(Car_ID)
);


INSERT INTO RentalHistory(Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('CR-005','2025-02-03','2025-02-05',105);
INSERT INTO RentalHistory(Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('CR-002','2025-03-15','2025-03-18',220);
INSERT INTO RentalHistory(Car_ID,START_DATE,END_DATE,RENTAL_AMOUNT)
VALUES('CR-004','2025-02-12','2025-02-16',125);


SELECT * FROM RentalHistory;

CREATE TABLE Admin(
       Admin_ID INT IDENTITY(1,1) PRIMARY KEY,
	   USER_NAME VARCHAR(255) NOT NULL,
	   PASSWORD VARCHAR(255) NOT NULL
);

SELECT * FROM Admin;

